name: Cypress CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: cypress/included:6.3.0
      options: --ipc=host
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          wait-on: 'http://localhost:3000'

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-snapshots
          path: cypress/snapshots

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
